// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateAutocompleteController from "./create_autocomplete_controller"
application.register("create-autocomplete", CreateAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import { Autocomplete } from "stimulus-autocomplete"
application.register("autocomplete", Autocomplete)