// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import { Autocomplete } from "stimulus-autocomplete"
application.register("autocomplete", Autocomplete)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ParticlesController from "./particles_controller"
application.register("particles", ParticlesController)
